// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Roman Calculator
Roman Calculator allows you to evaluate mathematical expressions with roman numbers (I, IV, V, X, L, C, M...). Expressions are evaluated according to BODMAS:
 - Brackets ()
 - Order ^
 - Multiplication *
 - Addition +
 - Subtraction -


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
