// Code generated by go-swagger; DO NOT EDIT.

package calc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CalcExprHandlerFunc turns a function with the right signature into a calc expr handler
type CalcExprHandlerFunc func(CalcExprParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CalcExprHandlerFunc) Handle(params CalcExprParams) middleware.Responder {
	return fn(params)
}

// CalcExprHandler interface for that can handle valid calc expr params
type CalcExprHandler interface {
	Handle(CalcExprParams) middleware.Responder
}

// NewCalcExpr creates a new http.Handler for the calc expr operation
func NewCalcExpr(ctx *middleware.Context, handler CalcExprHandler) *CalcExpr {
	return &CalcExpr{Context: ctx, Handler: handler}
}

/*CalcExpr swagger:route GET /calc calc calcExpr

Compute the result of an expression

*/
type CalcExpr struct {
	Context *middleware.Context
	Handler CalcExprHandler
}

func (o *CalcExpr) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCalcExprParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
