// Code generated by go-swagger; DO NOT EDIT.

package calc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "roman-calc/models"
)

// CalcExprOKCode is the HTTP code returned for type CalcExprOK
const CalcExprOKCode int = 200

/*CalcExprOK Result of computing the expression

swagger:response calcExprOK
*/
type CalcExprOK struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewCalcExprOK creates CalcExprOK with default headers values
func NewCalcExprOK() *CalcExprOK {

	return &CalcExprOK{}
}

// WithPayload adds the payload to the calc expr o k response
func (o *CalcExprOK) WithPayload(payload *models.Result) *CalcExprOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the calc expr o k response
func (o *CalcExprOK) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CalcExprOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CalcExprBadRequestCode is the HTTP code returned for type CalcExprBadRequest
const CalcExprBadRequestCode int = 400

/*CalcExprBadRequest Invalid request

swagger:response calcExprBadRequest
*/
type CalcExprBadRequest struct {
}

// NewCalcExprBadRequest creates CalcExprBadRequest with default headers values
func NewCalcExprBadRequest() *CalcExprBadRequest {

	return &CalcExprBadRequest{}
}

// WriteResponse to the client
func (o *CalcExprBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
