// Code generated by go-swagger; DO NOT EDIT.

package calc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCalcExprParams creates a new CalcExprParams object
// no default values defined in spec.
func NewCalcExprParams() CalcExprParams {

	return CalcExprParams{}
}

// CalcExprParams contains all the bound params for the calc expr operation
// typically these are obtained from a http.Request
//
// swagger:parameters calcExpr
type CalcExprParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Roman expression to calculate, e.g. "I*(II+III)"
	  Required: true
	  In: query
	*/
	Expr string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCalcExprParams() beforehand.
func (o *CalcExprParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qExpr, qhkExpr, _ := qs.GetOK("expr")
	if err := o.bindExpr(qExpr, qhkExpr, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindExpr binds and validates parameter Expr from query.
func (o *CalcExprParams) bindExpr(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("expr", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("expr", "query", raw); err != nil {
		return err
	}

	o.Expr = raw

	return nil
}
